# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
    container_name: devops_postgres
    image: postgres
    restart: always
    ports: 
        - 5432:5432
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: qwerty
        POSTGRES_DB: postgres

  adminer:
    container_name: devops_adminer
    image: adminer
    restart: always
    depends_on: 
        - db
    ports:
      - 9090:8080